from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(730, 389)
        self.label1 = QtWidgets.QLabel(Dialog)
        self.label1.setGeometry(QtCore.QRect(60, 20, 101, 21))
        self.label1.setObjectName("label1")
        self.lineEdit1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit1.setGeometry(QtCore.QRect(50, 60, 391, 22))
        self.lineEdit1.setObjectName("lineEdit1")
        self.pushButto1 = QtWidgets.QPushButton(Dialog)
        self.pushButto1.setGeometry(QtCore.QRect(350, 100, 93, 28))
        self.pushButto1.setObjectName("pushButto1")
        self.label2 = QtWidgets.QLabel(Dialog)
        self.label2.setGeometry(QtCore.QRect(60, 140, 131, 21))
        self.label2.setObjectName("label2")
        self.pushButton2 = QtWidgets.QPushButton(Dialog)
        self.pushButton2.setGeometry(QtCore.QRect(350, 220, 93, 28))
        self.pushButton2.setObjectName("pushButton2")
        self.lineEdit2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit2.setGeometry(QtCore.QRect(50, 180, 391, 22))
        self.lineEdit2.setObjectName("lineEdit2")
        self.pushButto3 = QtWidgets.QPushButton(Dialog)
        self.pushButto3.setGeometry(QtCore.QRect(350, 330, 93, 28))
        self.pushButto3.setObjectName("pushButto3")
        self.lineEdit3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit3.setGeometry(QtCore.QRect(50, 290, 391, 22))
        self.lineEdit3.setObjectName("lineEdit3")
        self.label3 = QtWidgets.QLabel(Dialog)
        self.label3.setGeometry(QtCore.QRect(60, 250, 121, 21))
        self.label3.setObjectName("label3")
        self.pushButtonglav = QtWidgets.QPushButton(Dialog)
        self.pushButtonglav.setGeometry(QtCore.QRect(560, 60, 93, 28))
        self.pushButtonglav.setObjectName("pushButtonglav")
        self.pushButtonNoglav = QtWidgets.QPushButton(Dialog)
        self.pushButtonNoglav.setGeometry(QtCore.QRect(560, 100, 93, 28))
        self.pushButtonNoglav.setObjectName("pushButtonNoglav")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label1.setText(_translate("Dialog", "Путь к шаблону"))
        self.pushButto1.setText(_translate("Dialog", "Выбрать"))
        self.label2.setText(_translate("Dialog", "Путь к данным Exsel"))
        self.pushButton2.setText(_translate("Dialog", "Выбрать"))
        self.pushButto3.setText(_translate("Dialog", "Выбрать"))
        self.label3.setText(_translate("Dialog", "Место сохранения"))
        self.pushButtonglav.setText(_translate("Dialog", "Выполнить"))
        self.pushButtonNoglav.setText(_translate("Dialog", "Выйти"))
